#!/bin/bash

readonly TMPDIR=/tmp/cooooooooooooooooooool

# unmount if tmpdir exists
if [ -e $TMPDIR ];
then
	echo "hi"
  fusermount -u $TMPDIR
  rm -rf $TMPDIR 2> /dev/null
# create the temp dir
else
	mkdir $TMPDIR
fi

# Create a disk and mount it to the given directory
make clean; make
./3600mkfs 1000

if [[ $# -eq 1 && $1 == "-d" ]]; then
  gdb --args ./3600fs -s -d $TMPDIR
else
	./3600fs -s -d $TMPDIR
fi
