#!/bin/bash

readonly TMPDIR=/tmp/numps

# create the temp dir
rm -rf $TMPDIR 2> /dev/null
mkdir $TMPDIR

# Create a disk and mount it to the given directory
make clean; make
./3600mkfs 1000
./3600fs -s -d $TMPDIR 
