#!/bin/bash

readonly TMPDIR=/tmp/bobby

# unmount if tmpdir exists
fusermount -zu $TMPDIR > /dev/null
rm -rf $TMPDIR > /dev/null
mkdir $TMPDIR > /dev/null

# Create a disk and mount it to the given directory
make clean; make
./3600mkfs 100000

if [[ $# -eq 1 && $1 == "-d" ]]; then
  gdb --args ./3600fs -s -d $TMPDIR
else
	./3600fs -s -d $TMPDIR
fi
